book/urls.py
from django.urls import path

from .views import book, book_json

urlpatterns = [
    path('book', book, name='book'),
    path('book.json', book_json, name='book_json'),
]

kegiatan/urls.py
from django.urls import path

from .views import index, tambah_kegiatan, tambah_anggota, hapus_kegiatan

urlpatterns = [
    path('', index, name='index'),
    path('tambah-kegiatan', tambah_kegiatan, name='tambah_kegiatan'),
    path('tambah-anggota/<str:kegiatan_id>', tambah_anggota, name='tambah_anggota'),
    path('hapus/<str:kegiatan_id>', hapus_kegiatan, name='hapus'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index),
    path('gallery', views.gallery),
    path('story1', views.story1)
]

matkul/urls.py
from django.urls import path

from .views import index, tambah_matkul, detail, hapus_matkul

urlpatterns = [
    path('', index, name='index'),
    path('tambah', tambah_matkul, name='tambah'),
    path('detail/<str:matkul_id>', detail, name='detail'),
    path('hapus/<str:matkul_id>', hapus_matkul, name='hapus'),
]

myaccor/urls.py
from django.urls import path

from .views import myaccor

app_name = 'myaccor'

urlpatterns = [
    path('', myaccor, name="accor"),
]

story_6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('matkul/', include('matkul.urls')),
    path('kegiatan/', include('kegiatan.urls')),
    path('myaccor/', include('myaccor.urls')),
    path('library/', include('book.urls')),
    path('userhandle/', include('userhandle.urls')),
    path('', include('main.urls')),
]

userhandle/urls.py
from django.urls import path

from .views import login, logout, register

app_name = 'userhandle'

urlpatterns = [
    path('register', register, name='register'),
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
]

book/models.py
from django.db import models

# Create your models here.

kegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=30)

class Person(models.Model):
    nama = models.CharField(max_length=30);
    kegiatan = models.ForeignKey('Kegiatan', on_delete=models.CASCADE)

main/models.py
from django.db import models

# Create your models here.

matkul/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class MataKuliah(models.Model):
    judul_matkul = models.CharField(max_length=30)
    nama_dosen = models.CharField(max_length=25)
    jumlah_sks = models.IntegerField(validators=[MinValueValidator(1)])
    deskripsi = models.CharField(max_length=144)
    semester_tahun = models.CharField(max_length=15)
    ruang_kelas = models.CharField(max_length=10)

myaccor/models.py
from django.db import models

# Create your models here.

userhandle/models.py
from django.db import models

# Create your models here.

kegiatan/forms.py
from django import forms
from .models import Kegiatan, Person

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'
        widgets = {
            'nama_kegiatan' : forms.TextInput(attrs={
                'class' : 'form-input'
            }),
        }
        

matkul/forms.py
from django import forms
from .models import MataKuliah

class MatkulForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = '__all__'
        widgets = {
            'judul_matkul' : forms.TextInput(attrs={
                'class' : 'form-input'
            }), 
            'nama_dosen' : forms.TextInput(attrs={
                'class' : 'form-input'
            }), 
            'jumlah_sks' : forms.NumberInput(attrs={
                'class' : 'form-input'
            }),
            'deskripsi' : forms.TextInput(attrs={
                'class' : 'form-input'
            }),
            'semester_tahun' : forms.TextInput(attrs={
                'class' : 'form-input'
            }),
            'ruang_kelas' : forms.TextInput(attrs={
                'class' : 'form-input'
            }),
        }

userhandle/forms.py
from django import forms
from .models import Kegiatan, Person

class LoginForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'
        widgets = {
            'nama_kegiatan' : forms.TextInput(attrs={
                'class' : 'form-input'
            }),
        }
        

book/views.py
import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect

def book(request):
    return render(request,"book/book.html")
    
def book_json(request):
    context = request.GET
    kata_kunci = context.get("q")
    response = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + kata_kunci)
    data = response.json()
    return JsonResponse(data)

kegiatan/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import KegiatanForm

from .models import Kegiatan, Person

def index(request):
    kegiatan_list = Kegiatan.objects.all()
    person_list = Person.objects.all()
    return render(request, 'kegiatan/index.html', {'kegiatan_list' : kegiatan_list, 'person_list' : person_list})

def tambah_kegiatan(request):
    if request.method == 'POST':
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/kegiatan')
    else:
        form = KegiatanForm()
    return render(request, 'kegiatan/tambah_kegiatan.html', {'form' : form})

def tambah_anggota(request, kegiatan_id):
    kegiatan = Kegiatan.objects.get(id=str(kegiatan_id))
    if request.method == 'POST':
        print(request.POST)
        Person.objects.create(nama=request.POST.get('nama'), kegiatan=kegiatan)
        return HttpResponseRedirect('/kegiatan')
    return render(request, 'kegiatan/tambah_anggota.html', {'kegiatan' : kegiatan})

def hapus_kegiatan(request, kegiatan_id):
    kegiatan = Kegiatan.objects.get(id=str(kegiatan_id))
    kegiatan.delete()
    
    return HttpResponseRedirect('/kegiatan')

main/views.py
from django.shortcuts import render

def index(request):
    return render(request,"main/index.html")

def gallery(request):
    return render(request,"main/gallery.html")

def story1(request):
    return render(request,"main/story1.html")

matkul/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import MatkulForm

from .models import MataKuliah

def index(request):
    matkul_list = MataKuliah.objects.all()
    return render(request, 'matkul/index.html', {'matkul_list' : matkul_list})

def tambah_matkul(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/matkul')
    else:
        form = MatkulForm()
    return render(request, 'matkul/tambah.html', {'form' : form})

def detail(request, matkul_id):
    matakuliah = MataKuliah.objects.get(id=str(matkul_id))
    
    return render(request, 'matkul/detail.html', {'matkul' : matakuliah})

def hapus_matkul(request, matkul_id):
    matakuliah = MataKuliah.objects.get(id=str(matkul_id))
    matakuliah.delete()
    
    return HttpResponseRedirect('/matkul')

myaccor/views.py
from django.shortcuts import render

def myaccor(request):
    return render(request,"myaccor/myaccor.html")

userhandle/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib.auth.models import User

def login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            django_login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect('/')
        else:
            context = {
                "error_message" : "Username atau password salah."
            }

    return render(request, 'userhandle/login.html', context)

def register(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.create_user(username=username, password=password)
        user.save()
        
        django_login(request, user)
        return HttpResponseRedirect('/')

    return render(request, 'userhandle/register.html', context)

def logout(request):
    django_logout(request)
    return HttpResponseRedirect("/")

book/templates/book/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'book/css/style.css' %}">
    <script src="{% static 'book/js/book.js' %}"></script>

    <title>My Books</title>

</head>
<body>
    <div class="main-container m-4 p-4">
        <div class="text-center my-4">
            <h1>My Library</h1>
            <input id="keyword" placeholder="Type here">
        </div>
        <table class="w-100 mt-4">
            <thead>
                <tr>
                    <th id="th1">Thumbnail</th>
                    <th id="th2">Title</th>
                    <th id="th3">Authors</th>
                    <th id="th4">Description</th>
                </tr>
            </thead>
            <tbody id="search_result"></tbody>
        </table>
    </div>
</body>
</html>

kegiatan/templates/kegiatan/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'kegiatan/css/style.css' %}">

    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-custom" role="navigation">
        <div class="container">
            <a class="navbar-brand d-md-none d-lg-block" href="/kegiatan">Kegiatan</a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="/kegiatan/tambah-kegiatan">Tambah Kegiatan</a></li>
                    <li class="nav-item"><a class="nav-link" href="/kegiatan">Daftar Kegiatan</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    {% block content %}{% endblock %}
</body>

kegiatan/templates/kegiatan/index.html
{% extends 'kegiatan/base.html' %}
{% load static %}

{% block head %}
<title>Daftar Kegiatan</title>
{% endblock %}

{% block content %}
{% if kegiatan_list %}
    {% for kegiatan in kegiatan_list %}
        <div class="container-fluid content-box col-md-4 col-12">
            <div class="judul">{{ kegiatan.nama_kegiatan }}</div>
            <div class="content-isi">
                <ul>
                    {% for anggota in person_list %}
                        {% if anggota.kegiatan == kegiatan %}
                            <li>{{ anggota.nama }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <form action="tambah-anggota/{{ kegiatan.id }}" method="GET">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Tambah Anggota">
                </form>
                <form action="hapus/{{ kegiatan.id }}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Hapus Kegiatan">
                </form>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="container-fluid content-box">
        <div class="judul">Tidak ada Kegiatan</div>
        <div class="content-isi">
            Silahkan tambahkan kegiatan di halaman tambah kegiatan.
        </div>
    </div>
{% endif %}
{% endblock %}

kegiatan/templates/kegiatan/tambah_anggota.html
{% extends 'kegiatan/base.html' %}
{% load static %}

{% block head %}
<title>Tambah Anggota</title>
{% endblock %}

{% block content %}
<div class="container-fluid content-box">
    <div class="judul">Tambah Anggota</div>
    <div class="content-isi">
        <form action="" method="POST">
            {% csrf_token %}
            <input type="text" class="form-input" maxlength="30" placeholder="Masukkan Nama Kamu" name="nama">
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</div>
{% endblock %}

kegiatan/templates/kegiatan/tambah_kegiatan.html
{% extends 'kegiatan/base.html' %}
{% load static %}

{% block head %}
<title>Tambah Kegiatan</title>
{% endblock %}

{% block content %}
<div class="container-fluid content-box">
    <div class="judul">Tambah Kegiatan</div>
    <div class="content-isi">
        <form action="tambah-kegiatan" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

{% endblock %}

{% block content %}
<div class="container-fluid content-box">
    <div class="judul">Moments</div>
    <div class="content-isi">
        <div class="row">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/o2n.png' %}" alt="O2N">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/station.png' %}" alt="station">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/pandora.png' %}" alt="pandora">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/arcade.png' %}" alt="arcade">
        </div>
    </div>
</div>
<div class="container-fluid content-box">
    <div class="judul">Travel</div>
    <div class="content-isi">
        <div class="row">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/sunset.png' %}" alt="sunset">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/bonfire.png' %}" alt="bonfire">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/cliff.png' %}" alt="cliff">
            <img class="col-sm-6 img-responsive" src="{% static 'assets/bali.png' %}" alt="bali-sunset">
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

main/templates/main/story1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style_story1.css' %}" />
    <title>Profile Budi</title>
</head>
<body>
    <header>
        <img src="{% static 'assets/foto-profil.jpg'%}">
        <h1>Budiman Arbenta</h1>
        <button class="backButton" onclick="goBack()">Go Back</button>

        <script>
            function goBack() {
              window.history.back();
            }
        </script>
    </header>

    <div class="profile">
        <h2>Profil</h2>
        <table>
            <tr>
                <td>Nama</td>
                <td>Budiman Arbenta</td>
            </tr>
            <tr>
                <td>NPM</td>
                <td>1906285535</td>
            </tr>
            <tr>
                <td>Angkatan</td>
                <td>Maung 2019</td>
            </tr>
            <tr>
                <td>Hobi</td>
                <td>Berenang</td>
            </tr>
            <tr>
                <td>Tempat Kuliah</td>
                <td>Fasilkom UI</td>
            </tr>
        </table>
    </div>

    <div class="description">
        <h2>Deskripsi Tentang Saya</h2>
        <p>
            Budi adalah mahasiswa yang memiliki minat pada bidang eksak sejak kecil. Dari minatnya tersebut, ia mulai mempelajari bidang informatika, terutama pada <i>competitive programming</i> dan <i>web development</i>. Saat ini Budi sedang mencari jalan yang ingin ditempuhnya setelah lulus kuliah.
        </p>
    </div>

    <div class="education">
        <h2>Riwayat Pendidikan</h2>
        <table>
            <tr>
                <td>2019 - sekarang</td>
                <td>Universitas Indonesia</td>
            </tr>
            <tr>
                <td>2016 - 2019</td>
                <td>SMA Kharisma Bangsa</td>
            </tr>
            <tr>
                <td>2013 - 2016</td>
                <td>SMP Negeri 1 Bandar Lampung</td>
            </tr>
            <tr>
                <td>2007 - 2013</td>
                <td>SD Tunas Mekar</td>
            </tr>
        </table>
    </div>

    <div class="social-media">
        <h2>Sosial Media</h2>
        <ul>
            <li><a href="https://www.instagram.com/budiiarb/"><img src="{% static 'assets/logo-instagram.png'%}"></a></li>
            <li><a href="https://www.linkedin.com/in/budiman-arbenta-a79195186/"><img src="{% static 'assets/logo-linkedin.png'%}"></a></li>
            <li><a href="http://wa.me/6285922147515"><img src="{% static 'assets/logo-whatsapp.png'%}"></a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100010368942788"><img src="{% static 'assets/logo-facebook.png'%}"></a></li>
            <li><a href="https://www.youtube.com/channel/UC2K54ryFsBc8qAkryYZfitg?view_as=subscriber"><img src="{% static 'assets/logo-youtube.png'%}"></a></li>
        </ul>
    </div>
</body>
</html>

matkul/templates/matkul/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'matkul/css/style.css' %}">

    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-custom" role="navigation">
        <div class="container">
            <a class="navbar-brand d-md-none d-lg-block" href="/matkul">Mata Kuliah</a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="/matkul/tambah">Tambah Mata Kuliah</a></li>
                    <li class="nav-item"><a class="nav-link" href="/matkul">Daftar Mata Kuliah</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container-fluid content-box">
        {% block content %}{% endblock %}
    </div>
</body>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Profile Budi</title>

    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <a class="navbar-brand d-md-none d-lg-block" href="/">PROFILEv2.0</a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="/#profile">Profile</a></li>
                    <li class="nav-item"><a class="nav-link" href="/#description">Deskripsi</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Riwayat
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item nav-link" href="/#pendidikan">Pendidikan</a><br>
                            <a class="dropdown-item nav-link" href="/#organisasi">Organisasi</a><br>
                            <a class="dropdown-item nav-link" href="/#kerja">Kerja</a>
                        </div>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="/#prestasi">Prestasi</a></li>
                    <li class="nav-item"><a class="nav-link" href="/#interest">Interest</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" href="gallery">Gallery</a></li>
                    <li class="nav-item"><a class="nav-link" href="/#project">Project</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="col-0 col-sm-3"></div>

        <div id="main" class="col-12 col-sm-6">
            <header class="text-center">
                <img class="img-responsive" src="{% static 'assets/foto-header.jpg' %}">
                <div class="pict-box">
                    <img id="prof-pict" class="img-circle" src="{% static 'assets/foto-profil.jpg' %}">
                </div>
                <div class="name">
                    <h1>Budiman Arbenta</h1>
                    <div class="row">
                        <div class="whitespace col-2"></div>
                        <div class="header-divider col-8"></div>
                        <div class="whitespace col-2"></div>
                    </div>
                    <h2>Mahasiswa Ilmu Komputer</h1>
                </div>
            </header>

            <section>
                {% block content %}{% endblock %}
            </section>

            <footer>
                <div id="contact" class="container-fluid contact-box">
                    <div class="judul">Contact</div>
                    <div class="contact-isi">
                        <table class="table table-borderless">
                            <tr>
                                <td class="col-lg-1"></td>
                                <td class="col-lg-2 contact-item"><img class="contact-icon img-responsive" src="static/assets/icon-mail.png"></td>
                                <td class="col-lg-4 contact-item">arbenta6@gmail.com</td>
                                <td class="col-lg-5"></td>
                            </tr>
                            <tr>
                                <td class="col-lg-1"></td>
                                <td class="col-lg-2 contact-item"><img class="contact-icon img-responsive" src="static/assets/icon-phone.png"></td>
                                <td class="col-lg-4 contact-item">085922147515</td>
                                <td class="col-lg-5"></td>
                            </tr>
                            <tr>
                                <td class="col-lg-1"></td>
                                <td class="col-lg-2 contact-item"><img class="contact-icon img-responsive" src="static/assets/icon-location.png"></td>
                                <td class="col-lg-4 contact-item">Jl. Margonda Raya No.48, RW.7, Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424</td>
                                <td class="col-lg-5"></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="social-media">
                    <ul class="social-media-list">
                        <li class="social-media-item">
                            <a class="col-2" href="https://www.instagram.com/budiiarb/"><img  class="social-media-logo" src="{% static 'assets/logo-instagram.png' %}"></a>
                        </li>
                        <li class="social-media-item">
                            <a class="col-2" href="https://www.linkedin.com/in/budiman-arbenta-a79195186/"><img  class="social-media-logo" src="{% static 'assets/logo-linkedin.png' %}"></a>
                        </li>
                        <li class="social-media-item">
                            <a class="col-2" href="http://wa.me/6285922147515"><img  class="social-media-logo" src="{% static 'assets/logo-whatsapp.png' %}"></a>
                        </li>
                        <li class="social-media-item">
                            <a class="col-2" href="https://www.facebook.com/profile.php?id=100010368942788"><img  class="social-media-logo" src="{% static 'assets/logo-facebook.png' %}"></a>
                        </li>
                        <li class="social-media-item">
                            <a class="col-2" href="https://www.youtube.com/channel/UC2K54ryFsBc8qAkryYZfitg?view_as=subscriber"><img  class="social-media-logo" src="{% static 'assets/logo-youtube.png' %}"></a>
                        </li>
                    </ul>
                </div>
            </footer>
        </div>

        <div class="col-0 col-sm-3"></div>
    </div>

    <div class="user-footer">
        {% if user.is_authenticated %}
        <span class="user-footer-label">Hi, {{ user.username }}</span>
        <span class="user-footer-item"><a href="{% url 'userhandle:logout' %}">Log Out</a></span>
        {% else %}
        <span class="user-footer-item"><a href="{% url 'userhandle:register' %}">Register</a></span>
        <span class="user-footer-item"><a href="{% url 'userhandle:login' %}">Log In</a></span>
        {% endif %}
    </div>
</body>
</html>